### ISSUE TITLE
Remove Platform Detection?

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/nuklear_gamepad#17]

**Comment by RobLoach** [comment]
@brianwatling What are your thoughts on completely disabling the platform detection for Gamepads? It would default always to `NK_GAMEPAD_NONE`, essentially.

**Comment by brianwatling** [comment]
I think it's great to have default / example implementations for common frameworks like SDL and GLFW so I'd say keep it unless it's too much work to maintain.

That said, the current approach relies on setting #defines before including the specific implementation. An alternative could be to accept a struct with function pointers so users must provide implementations. Then for SDL, GLFW, etc nuklear_gamepad can provide example/default implementations that can be selected by the user. In my project I essentially did this by defining the macros to a trampoline function (so two levels of indirection). Something like:

```c
typedef void (*nk_gamepad_update_fn)(void* user_data, struct nk_gamepads* gamepads)
// Add other function types here

struct nk_gamepad_callbacks {
  void* user_data;
  nk_gamepad_init_fn init;
  nk_gamepad_update_fn update;
  nk_gamepad_name_fn name;
  nk_gamepad_free_fn free;
}
```

Then for SDL, for example, you'd have something like:
```c
struct nk_gamepad_callbacks nk_gamepads_get_sdl_callbacks(void) {
  return (struct nk_gamepad_callbacks){
    .init = &nk_gamepad_sdl_init,
    ...
  };
}
```

**Comment by RobLoach** [comment]
Using callbacks instead is a fantastic idea. Would we still depend on the defines to set the initial gamepad callbacks?

**Comment by brianwatling** [comment]
Sent a PR. I left the main defines to pick the default implementation but users can also specify their own set of functions. Added a demo which uses NK_GAMEPAD_NONE, so no default implementation, and then demonstrates remapping buttons with the SDL implementation as a base
